language: go
go:
  - 1.12.x

git:
  depth: 5

services:
  - docker
before_install:
  - docker ps -a
install:
  - go get github.com/mattn/goveralls
script:
  - make dtest
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci