FROM golang:1.12-alpine

# Install git
RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates

# Set working directory
WORKDIR /go/src/github.com/MaksRybalkin/TravisTest/

# Run tests
CMD CGO_ENABLED=0 go test -v ./... -covermode=count -coverprofile=coverage.out